# Pre-commit hooks - Enforce quality BEFORE commit
# These run automatically on every commit

repos:
  # Python code formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--strict, --ignore-missing-imports]

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: [-r, claude_parser]

  # Check for large files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Test coverage enforcement
  - repo: local
    hooks:
      - id: pytest-coverage
        name: pytest with coverage
        entry: pytest tests/ --cov=claude_parser --cov-fail-under=90 --cov-report=term-missing
        language: system
        pass_filenames: false
        always_run: true

      - id: validate-spec
        name: validate specification compliance
        entry: python verify_spec.py
        language: system
        pass_filenames: false
        always_run: true

# Configuration
default_language_version:
  python: python3.11

fail_fast: false  # Run all hooks even if one fails
verbose: true     # Show output