# TRUE 95/5 Ruff Configuration - Only enable what we actually want to enforce

[lint]
# ONLY enable rules for actual functional issues
select = [
    "F821",     # Undefined names (breaks code)
    "F401",     # Unused imports (cleanup)  
    "E999",     # Syntax errors (breaks code)
    "W292",     # No newline at end (git issues)
]

# Test files can be even more relaxed
[lint.per-file-ignores]
"tests/*" = [
    "F841",     # Unused variables in tests (for clarity)
    "B011",     # assert False in tests (legitimate)
    "E722",     # Bare except in tests (robustness testing)
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"